version: '3'

services:
  backend:
    build: backend/
    environment:
      FIXER_HOST: http://data.fixer.io
      FIXER_ACCESS_KEY: ${FIXER_ACCESS_KEY}
    ports:
    - "8080:8080"

  frontend:
    build: frontend/
    ports:
    - "3000:80"
