# Displays a list of all created fees
GET http://localhost:8080/fees/
Content-Type: application/json
# Response example: {status: "OK", result: [{id: 1, from: "USD", to: "EUR", fee: 0.05}]}

###
# Creates fee
POST http://localhost:8080/fees/
Accept: application/json
Content-Type: application/json

{"from": "USD", "to": "EUR", "fee": 0.05}
# Response example: {status: "OK", result: {id: 1, from: "USD", to: "EUR", fee: 0.05}}

###
# Deletes fee
DELETE http://localhost:8080/fees/1
Content-Type: application/json
# Response example: {status: "OK"}

###
# Get all currencies
GET http://localhost:8080/currencies/
Content-Type: application/json
# Response example: {status: "OK", result: [{from: "USD", to: "EUR"}]}

###
# Convertion from one currency to another
POST http://localhost:8080/currencies/convert
Accept: application/json
Content-Type: application/json

{"amount": 100, "from": "USD", "to": "EUR"}
# Response example: {status: "OK", result: {"amount": 130}}

###
