currency-converter:
  defaultFee: 0.05
  fixer:
    host: ${FIXER_HOST:http://127.0.0.1:9999}
    accessKey: ${FIXER_ACCESS_KEY:mock_valid_key}
  currencies:
  - from: EUR
    to:
    - USD
    - RUB
